#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

GEXTRAS="$dir/data/cinnamon-extras.list"

# INSTALL CINNAMON COMPONENTS
function cinnamon {
echo ''
echo '1. Add Cinnamon PPA [Stable]?'
echo '2. Add Cinnamon Nightly PPA [Unstable]?'
echo '3. Install Cinnamon?'
echo '4. Install more Cinnamon components?'
echo 'r. Return.'
echo ''
read -p 'What would you like to do? (Enter your choice) : ' REPLY
case $REPLY in
# Add Cinnamon PPA [Stable]
1)
    # Add repository
    echo 'Adding Cinnamon PPA [Stable] to software sources...'
    show_info 'Requires root privileges:'
    sudo add-apt-repository -y ppa:lestcape/cinnamon
    # Update repository information
    echo 'Updating repository information...'
    sudo apt-get update
    show_success 'Done.'
    # Upgrade system?
    read -p 'Perform system upgrade? (Y)es, (N)o : ' REPLY
    case $REPLY in
    # Positive action
    [Yy]* )
        show_info 'Requires root privileges:'
        sudo apt-get dist-upgrade -y
        show_success 'Done.'
        cinnamon
        ;;
    # Negative action
    [Nn]* )
        clear && cinnamon
        show_success 'Done.'
        ;;
    # Error
    * )
        clear && show_error '\aSorry, try again.'
        cinnamon
        ;;
    esac
    ;;
# Add Cinnamon Nightly PPA [Unstable]
2)
    # Add repository
    echo 'Adding Cinnamon Nightly PPA [Unstable] to software sources...'
    show_info 'Requires root privileges:'
    sudo add-apt-repository -y ppa:gwendal-lebihan-dev/cinnamon-nightly
    # Update repository information
    echo 'Updating repository information...'
    sudo apt-get update
    show_success 'Done.'
    echo ''
    # Upgrade system?
    read -p 'Perform system upgrade? (Y)es, (N)o : ' REPLY
    case $REPLY in
    # Positive action
    [Yy]* )
        show_info 'Requires root privileges:'
        sudo apt-get dist-upgrade -y
        show_success 'Done.'
        cinnamon
        ;;
    # Negative action
    [Nn]* )
        clear && cinnamon
        show_success 'Done.'
        ;;
    # Error
    * )
        clear && show_error '\aSorry, try again.'
        cinnamon
        ;;
    esac
    ;;
# Install CINNAMON
3)
    echo 'Installing Cinnamon...'
    show_info 'Requires root privileges:'
    sudo apt-get install -y cinnamon
    show_success 'Done.'
    echo ''
    cinnamon
    ;;
# Install extra Cinnamon components
4)
    echo 'Installing extra Cinnamon components...'
    echo ''
    echo 'Current package list:'
    echo ''
    for package in $(cat $GEXTRAS)
    do 
    echo -e '\t'$package
    done
    echo ''
    show_info 'Proceed? (Y)es, (N)o : ' && read REPLY
    echo ''
    case $REPLY in
    # Positive action
    [Yy]* )
        show_info 'Requires root privileges:'
        # Feel free to change the contents of "cinnamon-extras.list" to whatever suits your preferences.
        sudo apt-get install -y $(cat $GEXTRAS)
        show_success 'Done.'
        cinnamon
        ;;
    # Negative action
    [Nn]* )
        clear && cinnamon
        ;;
    # Error
    * )
        clear && show_error '\aSorry, try again.'
        cinnamon
        ;;
    esac
    ;;
# Return
[Rr]*) 
    clear && main;;
# Invalid choice
* ) 
    clear && show_error '\aNot an option, try again.' && cinnamon;;
esac
}
