#!/bin/bash

# THIRD PARTY APPLICATIONS
function thirdparty {
echo ''
show_info 'What would you like to install? '
echo ''
echo '1. BleachBit'
echo '1. Google Chrome'
echo '2. Google Talk Plugin'
echo '3. Steam'
echo '4. Sublime Text 3 (build 3065)'
echo '5. Minecraft Installer'
echo '6. Birdie'
echo 'x7. SVG Cleaner'
echo 'r. Return'
echo ''
show_info 'Enter your choice:' && read REPLY
case $REPLY in
# BleachBit
1)
    echo 'Installing BleachBit...'
    sudo apt-get install -y bleachbit
    show_success 'Done.'
    thirdparty
    ;;
### Driver Intel For [12.04/12.10/13.04/13.10] (Official)
# Source: https://01.org/linuxgraphics/downloads
1)
    # Add repository
    echo 'Adding Intel Driver Repository to software sources...'
    sudo sh -c 'echo "deb https://download.01.org/gfx/ubuntu/14.04/main/ trusty main" > /etc/apt/sources.list.d/intellinuxgraphics.list'

    # Add Authentication keys
    echo 'Adding authentication keys...'
    wget --no-check-certificate https://download.01.org/gfx/RPM-GPG-KEY-ilg -O - | sudo apt-key add -

    # Update repository information
    echo 'Updating repository information...'
    sudo apt-get update
    # Install
    echo 'Installing Google Chrome...'
    sudo apt-get -y upgrade
    sudo apt-get -y dist-upgrade
    show_success 'Done.'
    thirdparty
    ;;


    echo 'Downloading Intel Driver...'
    # Download Debian file that matches system architecture
    case `uname -i` in
        i386|i486|i586|i686)
            wget -O /tmp/intel-linux-graphics-installer.deb https://download.01.org/gfx/ubuntu/14.04/main/pool/main/i/intel-linux-graphics-installer/intel-linux-graphics-installer_1.0.7-0intel1_amd64.deb
            ;;
        x86_64)
            wget -O /tmp/intel-linux-graphics-installer.deb https://download.01.org/gfx/ubuntu/14.04/main/pool/main/i/intel-linux-graphics-installer/intel-linux-graphics-installer_1.0.7-0intel1_i386.deb
            ;;
        *)
            show_error "Couldn't find a download that matches your system." && thirdparty
            ;;
    esac
    # Add Authentication keys
    echo 'Adding authentication keys...'
    wget --no-check-certificate https://download.01.org/gfx/RPM-GPG-KEY-ilg -O - | sudo apt-key add -
    # Install package(s)
    echo 'Installing Intel Driver...'
    sudo apt-get install ttf-ancient-fonts -y
    sudo dpkg -i /tmp/intel-linux-graphics-installer.deb
    sudo apt-get install -fy
    echo 'Starting Intel Driver Installer... Follow their steps'
    sudo intel-linux-graphics-installer
    # Cleanup and finish
    echo 'Installing Intel Driver...'
    rm /tmp/intel-linux-graphics-installer.deb
    show_success 'Done.'
    thirdparty
    ;;
# Google Chrome
1) 
    # Add repository
    echo 'Adding Google Chrome Repository to software sources...'
    sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

    # Add Authentication keys
    echo 'Adding authentication keys...'
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

    # Update repository information
    echo 'Updating repository information...'
    sudo apt-get update
    # Install
    echo 'Installing Google Chrome...'
    sudo apt-get install -y google-chrome-stable
    show_success 'Done.'
    thirdparty
    ;;
# Google Talk Plugin
2)
    # Add repository
    echo 'Adding Google Talk Plugin Repository to software sources...'
    show_info 'Requires root privileges:'
    sudo sh -c 'echo "deb http://dl.google.com/linux/talkplugin/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

    # Add Authentication keys
    echo 'Adding authentication keys...'
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

    # Update repository information
    echo 'Updating repository information...'
    sudo apt-get update
    # Install
    echo 'Installing Google Talk Plugin...'
    sudo apt-get install -y google-talkplugin
    show_success 'Done.'
    thirdparty
    ;;
# Steam
3)
    # Add repository
    echo 'Adding Steam Repository to software sources...'
    show_info 'Requires root privileges:'
    sudo sh -c 'echo "deb http://repo.steampowered.com/steam/ precise steam" >> /etc/apt/sources.list.d/steam.list' 

    # Add Authentication keys
    echo 'Adding authentication keys...'
    wget -q -O http://repo.steampowered.com/steam/signature.gpg && sudo apt-key add -
    #sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B05498B7

    # Update repository information
    echo 'Updating repository information...'
    sudo apt-get update
    # Install
    echo 'Installing Steam...'
    sudo apt-get install -y steam
    show_success 'Done.'
    thirdparty
    ;;
# Sublime Text 3
4)
    # Add repository
    echo 'Adding Sublime Text 3 PPA to software sources...'
    show_info 'Requires root privileges:'
    sudo add-apt-repository ppa:webupd8team/sublime-text-3 

    # Update repository information
    echo 'Updating repository information...'
    sudo apt-get update
    # Install
    echo 'Installing Sublime Text 3...'
    sudo apt-get install -y sublime-text-installer
    show_success 'Done.'
    thirdparty
    ;;
# Minecraft Installer
5)
    # Add repository
    echo 'Adding Minecraft Installer PPA to software sources...'
    show_info 'Requires root privileges:'
    sudo add-apt-repository ppa:minecraft-installer-peeps/minecraft-installer
    # Update repository information
    echo 'Updating repository information...'
    sudo apt-get update
    # Install
    echo 'Installing Minecraft Installer...'
    sudo apt-get install -y minecraft-installer
    show_success 'Done.'
    thirdparty
    ;;
# Birdie
6)
    # Add repository
    echo 'Adding Birdie Team PPA to software sources...'
    show_info 'Requires root privileges:'
    sudo add-apt-repository ppa:birdie-team/stable
    # Update repository information
    echo 'Updating repository information...'
    sudo apt-get update
    # Install
    echo 'Installing Birdie...'
    sudo apt-get install -y birdie
    show_success 'Done.'
    thirdparty
    ;;
# Synaptic - lighter than software center, better descriptions
7)
    echo 'Installing Synaptic...'
    sudo apt-get -y install synaptic
    show_success 'Done.'
    thirdparty
    ;;
# build-essential - Setup the system to handle compiling and installing from source.
7)
    echo 'Installing build-essential...'
    sudo apt-get -y install build-essential
    show_success 'Done.'
    thirdparty
    ;;

# Chromium
7)
    echo 'Installing Chromium...'
    sudo apt-get -y install chromium-browser
    show_success 'Done.'
    thirdparty
    ;;
# Virtualbox
7)
sudo adduser x vboxusers
    echo 'Installing Chromium...'
    sudo apt-get -y install chromium-browser
    show_success 'Done.'
    thirdparty
    ;;
# Java [Oracle]
7)
    echo 'Installing Chromium...'
    sudo apt-get -y install chromium-browser
    show_success 'Done.'
    thirdparty
    ;;
# Enable DVD Playback in Ubuntu
7)
    # Add repository
    echo 'Adding libdvdcss Repository to software sources...'
    echo "deb http://download.videolan.org/pub/ubuntu/stable ./" | sudo tee /etc/apt/sources.list.d/libdvdcss.list
    # Add Authentication keys
    echo 'Adding authentication keys...'
    wget -q -O http://download.videolan.org//pub/debian/videolan-apt.asc && sudo apt-key add -
    # Update repository information
    echo 'Updating repository information...'
    sudo apt-get update
    echo 'Installing libdvdcss2...'
    sudo apt-get install libdvdcss2
    show_success 'Done.'
#sudo /usr/share/doc/libdvdread4/install-css.sh
    thirdparty
    ;;

#Part 2 - Install Virtualbox additions
sudo apt-get install build-essential dkms linux-headers-`uname -r`
 

# Return
[Rr]*) 
    clear && main;;
# Invalid choice
* ) 
    clear && show_error '\aNot an option, try again.' && thirdparty;;
esac
}
